default: &default
  adapter: mysql2
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock
  username: acredisrails5
  password: acredisrails5
  pool: 5
  host: mysql


development:
  <<: *default
  database: acredisrails5_development

#test:
#  <<: *default
#  database: acredisrails5_test